Clang 4.0.0 fix for Bochs
Clang 4.0.0, which ac++ links against since today, throws an error in
the Bochs code.

config.cc:3480:55: error: ordered comparison between pointer and zero ('char *' and 'int')
    if (SIM->get_param_string("model", base)->getptr()>0) {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~

Change-Id: I8404a54acd468bf71cbf29867657f9458f3a4c3f